/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { LoginControllerService } from './services/login-controller.service';
export { TarsashazakService } from './services/tarsashazak.service';
export { MainControllerService } from './services/main-controller.service';
