/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApartmentFilterRequest } from '../../models/apartment-filter-request';
import { Pageable } from '../../models/pageable';
import { PageApartmentListResponse } from '../../models/page-apartment-list-response';

export interface GetAllApartments$Params {
  filterRequest: ApartmentFilterRequest;
  pageable: Pageable;
}

export function getAllApartments(http: HttpClient, rootUrl: string, params: GetAllApartments$Params, context?: HttpContext): Observable<StrictHttpResponse<PageApartmentListResponse>> {
  const rb = new RequestBuilder(rootUrl, getAllApartments.PATH, 'get');
  if (params) {
    rb.query('filterRequest', params.filterRequest, {});
    rb.query('pageable', params.pageable, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageApartmentListResponse>;
    })
  );
}

getAllApartments.PATH = '/apartment/list';
