/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApartmentResponse {
  address?: string;
  apartmentIdentifier?: string;
  baseAddress?: string;
  cadastralNumber?: string;
  city?: string;
  dataEntryStartDate?: string;
  dedicatedEmail?: string;
  id?: string;
  isActive?: boolean;
  isHousingCooperative?: boolean;
  name?: string;
  postalCode?: string;
  residentAccessStartDate?: string;
  taxNumber?: string;
}
