/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApartmentRequest {

  /**
   * Társasház azonosító (opcionális, belső használatra)
   */
  apartmentIdentifier?: string;

  /**
   * Bázis cím, albetétek címéhez
   */
  baseAddress?: string;

  /**
   * Helyrajzi szám
   */
  cadastralNumber?: string;

  /**
   * Település
   */
  city: string;

  /**
   * Adatrögzítés indítása (hónap)
   */
  dataEntryStartMonth?: string;

  /**
   * Társasház dedikált e-mail címe
   */
  dedicatedEmail?: string;

  /**
   * Lakásszövetkezet
   */
  isHousingCooperative?: boolean;

  /**
   * Társasház neve
   */
  name: string;

  /**
   * Irányítószám
   */
  postalCode?: string;

  /**
   * Lakói hozzáférés indítása (hónap)
   */
  residentAccessStartMonth?: string;

  /**
   * Közterület neve és házszám
   */
  streetAndNumber: string;

  /**
   * Adószám
   */
  taxNumber?: string;
}
