/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApartmentFilterRequest {

  /**
   * Társasház azonosító (opcionális, belső használatra)
   */
  apartmentIdentifier?: string;

  /**
   * Település
   */
  city: string;

  /**
   * Társasház neve
   */
  name: string;

  /**
   * Irányítószám
   */
  postalCode?: string;
}
