/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApartmentListResponse {
  address?: string;
  bankImportStatus?: string;
  id?: string;
  lastBookkeepingDate?: string;
  lastStatementDate?: string;
  name?: string;
  navImportStatus?: string;
  pinCode?: string;
}
