/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApartmentResponse } from '../../models/apartment-response';

export interface GetApartmentById$Params {
  id: string;
}

export function getApartmentById(http: HttpClient, rootUrl: string, params: GetApartmentById$Params, context?: HttpContext): Observable<StrictHttpResponse<ApartmentResponse>> {
  const rb = new RequestBuilder(rootUrl, getApartmentById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApartmentResponse>;
    })
  );
}

getApartmentById.PATH = '/apartment/{id}';
